; generated by DCC v0.1 alpha

.text

.global maxOfTwo

maxOfTwo:

        pushq %rbp

        movq %rsp, %rbp

        subq $8, %rbp

        pushq %r12

        pushq %r13

        pushq %r14

        pushq %r15

        movq %rdi, -4(%rbp)

        movq %rsi, -8(%rbp)

        movq $0, %r10

        cmp -8(%rbp), -4(%rbp)

        cmovl $1, %r10

        cmp %r10, $0

        je L1

        movq -8(%rbp), -4(%rbp)

        jmp L0

        jmp L2

L1:

        movq -4(%rbp), -8(%rbp)

        jmp L0

L2:

L0:

        movq -8(%rbp), %rax
        popq %r15

        popq %r14

        popq %r13

        popq %r12

        mov %rbp, %rsp

        popq %rbp

        ret

.global main

main:

        pushq %rbp

        movq %rsp, %rbp

        subq $8, %rbp

        pushq %r12

        pushq %r13

        pushq %r14

        pushq %r15

        movq $420, %rdi

        movq $69, %rsi

        push %r10

        push %r11

        xor %rax, %rax

        call maxOfTwo

        pop %r11

        pop %r10

        movq %rax, %r10

        movq %r10, -4(%rbp)

        movq $0, -8(%rbp)

        jmp L3

L3:

        movq -8(%rbp), %rax
        popq %r15

        popq %r14

        popq %r13

        popq %r12

        mov %rbp, %rsp

        popq %rbp

        ret
