; generated by DCC v0.1 alpha

.text

.global maxOfTwo

maxOfTwo:

        pushq %rbp

        movq %rsp, %rbp

        subq $8, %rbp

        pushq %r12

        pushq %r13

        pushq %r14

        pushq %r15

        movl %edi, -4(%rbp)

        movl %esi, -8(%rbp)

        movl $0, %r10d

        cmp -8(%rbp), -4(%rbp)

        cmovl $1, %r10d

        cmp %r10d, $0

        je L1

        movl -8(%rbp), -4(%rbp)

        jmp L0

        jmp L2

L1:

        movl -4(%rbp), -8(%rbp)

        jmp L0

L2:

L0:

        movl -8(%rbp), %eax
        popq %r15

        popq %r14

        popq %r13

        popq %r12

        movq %rbp, %rsp

        popq %rbp

        ret

.global main

main:

        pushq %rbp

        movq %rsp, %rbp

        subq $8, %rbp

        pushq %r12

        pushq %r13

        pushq %r14

        pushq %r15

        movl $420, %edi

        movl $69, %esi

        pushq %r10

        pushq %r11

        xor %rax, %rax

        call maxOfTwo

        popq %r11

        popq %r10

        movl %eax, %r10d

        movl %r10d, -4(%rbp)

        movl $0, -8(%rbp)

        jmp L3

L3:

        movl -8(%rbp), %eax
        popq %r15

        popq %r14

        popq %r13

        popq %r12

        movq %rbp, %rsp

        popq %rbp

        ret
